- hosts: webapp
  become: yes
  gather_facts: yes
  vars:
    golang_version: 1.13

  roles:
    - user.isucon
    - bootstrap
    - dev.deploy
    - initial-data

    - nginx
    - mysql
    - golang
    - perl
    - php
    - ruby
    - python
    - nodejs
    - webapp.mysql
    - webapp.golang
    - webapp.perl
    - webapp.php
    - webapp.ruby
    - webapp.python
    - webapp.nodejs
    - webapp.nginx

    # for dev
    # - nginx.log-format
    # - external.nginx
    # - external.shipment
    # - external.payment

    # for benchmarker
    - external.benchmarker

  tasks:
    - name: Start default daemons
      become: yes
      become_user: root
      systemd:
        name: "{{ item }}"
        state: restarted
        daemon_reload: yes
        enabled: yes
      loop:
        - nginx.service
        - mysql.service
        - isucari.golang.service
        # - shipment.service
        # - payment.service
