- hosts: webapp
  become: yes
  gather_facts: yes

  roles:
    - user.isucon
    - bootstrap
    - webapp.deploy

    - nginx
    - mysql
    - golang
    - perl
    - php
    - ruby
    - python
    - nodejs
    - webapp.mysql
    - webapp.golang
    - webapp.perl
    - webapp.php
    - webapp.ruby
    - webapp.python
    - webapp.nodejs
    - webapp.nginx

  tasks:
    - name: Start default daemons
      become: yes
      become_user: root
      systemd:
        name: "{{ item }}"
        state: restarted
        daemon_reload: yes
        enabled: yes
      with_items:
        - nginx.service
        - mysql.service
        - isucari.golang.service
