---
- name: mkdir /usr/local/go
  file: path=/usr/local/go state=directory

- name: check uname
  shell: uname -s | tr [A-Z] [a-z]
  register: uname_res
  check_mode: no

- name: check arch
  command: dpkg --print-architecture
  register: arch_res
  check_mode: no

- name: download go binary
  unarchive:
    src="https://golang.org/dl/go1.24.3.{{ uname_res.stdout }}-{{ arch_res.stdout }}.tar.gz"
    dest=/usr/local/
    remote_src=yes

- name: Add PATH for go
  become: yes
  become_user: isucon
  blockinfile:
    marker: "# {mark} ANSIBLE MANAGED BLOCK go"
    dest: /home/isucon/.bashrc
    content: |
      export PATH=/usr/local/go/bin:$PATH
