- name: Create Directory for TLS Certificate and Key
  file:
    path: /etc/nginx/ssl
    state: directory
    owner: root
    group: root
    mode: 0700

- name: Download SSL certificates from GitHub
  get_url:
    url: "{{ item.url }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: '0600'
  loop:
    - { url: 'https://github.com/KOBA789/t.isucon.pw/releases/latest/download/fullchain.pem', dest: '/etc/nginx/ssl/fullchain.pe' }
    - { url: 'https://github.com/KOBA789/t.isucon.pw/releases/latest/download/key.pem', dest: '/etc/nginx/ssl/key.pe' }

- name: Copy Nginx script
  copy:
    src: etc/nginx/update_cert.sh
    dest: /etc/nginx/update_cert.sh
    owner: root
    group: root
    mode: 0755
