version: '2'
services:
  db:
    image: mariadb:10.5.5
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
  web:
    build: .
    command: 'rackup -o 0.0.0.0 -p 3000 config.ru'
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
    environment:
      MYSQL_HOST: db