
$disable_unattended_upgrades =<<-SCRIPT
echo "-- Disabling unattended upgrades --"
cat << EOF > /etc/apt/apt.conf.d/51disable-unattended-upgrades
APT::Periodic::Update-Package-Lists "0";
APT::Periodic::Unattended-Upgrade "0";
EOF
SCRIPT

Vagrant.configure(2) do |config|
  config.vm.box = "bento/ubuntu-18.04"
  config.vm.provider "virtualbox" do |vm|
    vm.name   = "isucon9-quarifier"
    vm.cpus   = 4
    vm.memory = 2048
  end
  config.vm.hostname = "isucon9-quarifier"

  config.vm.provision :shell, inline: $disable_unattended_upgrades
  config.vm.provision :file,  source: "./roles/", destination: "/tmp/ansible/roles"
  config.vm.provision :file,  source: "./site.yml", destination: "/tmp/ansible/site.yml"
end
